Выполнены задания по 4му спринту
DzhamiRakhmetov/MovieQuiz-ios pull request #2
Opened 2022-11-19 09:19 UTC by DzhamiRakhmetov

2022-11-19 09:58 UTC, mmbabaev commented
картинки имеют белые области. Нужно поставить у image view content mode aspectFill

2022-11-19 09:59 UTC, mmbabaev commented
У корневой StackView не хватает bottom constraint до safe area

2022-11-19 10:00 UTC, mmbabaev commented
Также шрифты не меняются в приложении. В учебнике допущена ошибка, поэтому этот пункт необязателен. 
На скрине показал как нужно сделать: 
1) Шрифты добавлены в Group (серая папка)
2) Шрифтам проставлена галочка Target Membership  (справа)

<img width="1356" alt="Screen Shot 2022-11-17 at 20 15 01" src="https://user-images.githubusercontent.com/12600807/202513128-d74c5681-7a76-4778-ae5b-0fbcd44f0893.png">

Полезная статья, которая помогла мне разобраться в свое время: 
https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

2022-11-19 10:00 UTC, mmbabaev requested changes

2022-11-19 10:00 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction func noButtonClicked(_ sender: UIButton) {
порядок в viewController обычно делают такой: 

1. Properties
2. override funcs
3. IBAction funcs
4. other funcs

2022-11-19 10:00 UTC, mmbabaev commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                                                        <integer key="value" value="15"/>
неверное значение закругления рамки

2022-11-19 10:00 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Необязательно: если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-21 10:27 UTC, DzhamiRakhmetov commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Правильно понимаю что метод в DispatchQueue рабочий, но так же можно прописать 
.isEnabled = true

Вопрос:
допустим заместо DispatchQueue мы решаем использовать isEnabled в методе showAnswerResult is Correct 
как тогда прописать данное свойство, actionButton.isEnabled = true или отдельно под каждое @IBAction, тк потом данный метод вызывается в кнопках?

2022-11-21 10:29 UTC, DzhamiRakhmetov commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                                                        <integer key="value" value="15"/>
![Снимок экрана 2022-11-21 в 17 28 40](https://user-images.githubusercontent.com/101446127/203027674-26e3f570-abb6-477b-ad3a-d668900a98a7.png)
![Снимок экрана 2022-11-21 в 17 28 35](https://user-images.githubusercontent.com/101446127/203027682-c59a1d84-b4f6-453c-b69d-51fa5737d173.png)

2022-11-22 05:36 UTC, mmbabaev commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                                                        <integer key="value" value="15"/>
Прошу прощения, возможно перепутал с основной картинкой

2022-11-22 18:16 UTC, DzhamiRakhmetov commented
Выполнены задания по 4му спринту

2022-11-22 18:16 UTC, merged